# Generated by Django 3.2.6 on 2021-10-27 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analiza_zemljišta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_analize', models.CharField(max_length=5)),
                ('datum_analize', models.CharField(max_length=11)),
                ('parcela', models.CharField(max_length=30)),
                ('pH_M_KCL', models.IntegerField(default=4)),
                ('pH_H_H2O', models.IntegerField(default=4)),
                ('Humus_procent', models.IntegerField(default=4)),
                ('CaCO3_procent', models.IntegerField(default=4)),
                ('Azot_procent', models.IntegerField(default=4)),
                ('Fosfor_procent', models.IntegerField(default=4)),
                ('Kalij_procent', models.IntegerField(default=4)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
