# Generated by Django 3.2.6 on 2021-11-01 15:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiza_zemljišta',
            name='korisnik',
            field=models.ForeignKey(limit_choices_to=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
