# Generated by Django 3.2.6 on 2021-11-01 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korisnici', '0004_alter_analiza_zemljišta_korisnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiza_zemljišta',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
