# Generated by Django 3.2.6 on 2021-11-05 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korisnici', '0005_alter_analiza_zemljišta_korisnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrada_mr_prostora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.CharField(default=2011, max_length=4)),
                ('parcela', models.CharField(max_length=30)),
                ('vrsta_kulture', models.CharField(max_length=30)),
                ('starost_zasada', models.CharField(max_length=30)),
                ('trava', models.CharField(max_length=30)),
                ('period_kosenja', models.CharField(max_length=30)),
                ('folija_malc', models.CharField(max_length=30)),
                ('kultiviranje', models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=2)),
                ('plitko_oranje', models.CharField(choices=[('DA', 'DA'), ('NE', 'NE')], default='NE', max_length=2)),
                ('datum', models.DateField(default=10.1)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
