# Generated by Django 3.2.6 on 2021-11-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0006_obrada_mr_prostora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrada_mr_prostora',
            name='datum',
            field=models.CharField(default='10.10.2021.', max_length=11),
        ),
    ]
